# Generated by Django 4.0 on 2022-01-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0003_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='blog.tag')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='auth.user')),
            ],
        ),
    ]
