# Generated by Django 4.0 on 2022-01-26 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
